"""empty message

Revision ID: 174ada9949ac
Revises: 
Create Date: 2022-02-25 23:28:35.160449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '174ada9949ac'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('member',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('pwd', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('tel', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('field',
    sa.Column('user', sa.String(length=50), nullable=False),
    sa.Column('field_name', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['user'], ['member.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user')
    )
    op.create_table('newsDB',
    sa.Column('num', sa.Integer(), nullable=False),
    sa.Column('user', sa.String(length=50), nullable=True),
    sa.Column('news_img_url', sa.String(length=100), nullable=False),
    sa.Column('news_title', sa.String(length=100), nullable=False),
    sa.Column('news_content', sa.String(length=100), nullable=False),
    sa.Column('news_reporter', sa.String(length=50), nullable=False),
    sa.Column('news_date', sa.String(length=50), nullable=False),
    sa.Column('news_url', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['user'], ['member.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('num')
    )
    op.create_table('officeDB',
    sa.Column('num', sa.Integer(), nullable=False),
    sa.Column('user', sa.String(length=50), nullable=True),
    sa.Column('office_name', sa.String(length=30), nullable=False),
    sa.Column('office_apply', sa.String(length=30), nullable=False),
    sa.Column('office_referee', sa.String(length=30), nullable=False),
    sa.Column('office_score', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['user'], ['member.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('num')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('officeDB')
    op.drop_table('newsDB')
    op.drop_table('field')
    op.drop_table('member')
    # ### end Alembic commands ###
