"""empty message

Revision ID: 2c24880e3aad
Revises: 
Create Date: 2022-02-24 14:42:35.377125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c24880e3aad'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('keyword',
    sa.Column('num', sa.Integer(), nullable=False),
    sa.Column('year', sa.String(length=20), nullable=False),
    sa.Column('keyword', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('num')
    )
    op.create_table('member',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('pwd', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('tel', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('member')
    op.drop_table('keyword')
    # ### end Alembic commands ###
